name: Continuous Bot Runtime

on:
  workflow_dispatch: # كيشغل البوت بيدك وقت ما بغيتي

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install Project Dependencies
      run: npm install

    - name: Start Turbo Engine
      run: node index.js
