name: Continuous Bot Runtime

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *' # هادي زيادة أمان كتعاود تشغل البوت أوتوماتيكياً كل 5 سوايع وخا تنساه

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install FFmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Install Project Dependencies
      run: npm install

    - name: Start Turbo Engine
      run: node index.js

    - name: Auto-Trigger Next Session (Loop)
      if: always() # وخا يطفى السكريبت كيمشي يعاود يطلق راسه لـ 6 سوايع خرى
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/run.yml/dispatches \
        -d '{"ref":"main"}'
